// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EncryptIt
{
    internal sealed partial class Vsix
    {
        public const string Id = "EncryptIt";
        public const string Name = "EncryptIt";
        public const string Description = @"Quick tool to encrypt a string using Data Protection APIs on Windows.  Machine/user specific.";
        public const string Language = "en-US";
        public const string Author = "Tim Heuer";
        public const string Tags = "tools";
    }
}
